#pragma once
#include <vector>
#include <string>
#include <cmath>
#include <algorithm>
#include <iostream>
#include <iterator>
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <fstream>
#include <sstream>
#include <time.h>
#include <array>

#include "ir_track.h"
#include "blob_lib.h"
#include "video_lib.h"
#include "kalman_lib.h"
#include "mono_calib.h"
